Alternate fix for import highlighting with instantiations
github/vscode-codeql pull request #2859
Opened 2023-09-25 22:43 UTC by dbartol

This is an alternate fix for https://github.com/github/vscode-codeql/pull/2792. It updates the heuristic for finding the end of an import directive. The new heuristic matches a zero-width string that is preceded by a character that could end the import directive (identifier, `>`) and is not followed by a character that would continue the import directive (`,`, `.`, `<`, `::`).

2023-10-06 09:44 UTC, ginsbach requested changes
Thanks a lot for looking into this! Apologies for taking a bit of time to get back to you. I have this one minor suggestion, aside from that it looks good to me.

2023-10-06 09:44 UTC, ginsbach commented on extensions/ql-vscode/syntaxes/ql.tmLanguage.yml
> +    # `<`, `,`, or `::`. This works for nearly all real-world `import` directives, but it will end the
I think we also need '>' in that list of allowed next tokens. After all, we could import a nested instanitation
```ql
bindingset[this]
signature class TSig;

module M1<TSig T> {
  class type = T;
}

module M2 {
  import M1<M1<int>>
}
```

2023-10-06 11:34 UTC, ginsbach commented on extensions/ql-vscode/syntaxes/ql.tmLanguage.yml
> +    # `<`, `,`, or `::`. This works for nearly all real-world `import` directives, but it will end the
Actually, it seems there is no discernible difference, and even the compiled grammar stays the same if I add '>'.

2023-10-06 11:47 UTC, ginsbach approved these changes
I am approving this issue to signal that I'm happy with the changes, but there is no need to merge - I have already updated [my branch](https://github.com/github/vscode-codeql/pull/2792)

2023-10-09 21:17 UTC, dbartol commented
Closing since this was already merged into the real PR

2023-10-09 21:17 UTC, closed without merging