Add some commonly used QL snippets
github/vscode-codeql pull request #782
Opened 2021-03-16 10:10 UTC by edoardopirovano

This PR addresses #392 by introducing some simple snippets for query metadata, classes, from/where/select statements, predicates, dataflow/taint tracking classes, and all the aggregates and quantifiers.

2021-03-16 16:52 UTC, aeisenberg requested changes
This looks nicely comprehensive. Thanks!

I think in general, any snippet placeholder that _must_ be added should have a default value. If nothing else, this just signifies where a user can edit.

2021-03-16 16:52 UTC, aeisenberg commented on extensions/ql-vscode/snippets.json
> +      " * @kind $3",
Either add a _choice_ here, or separate this into multiple snippets, one for each metadata kind.

https://code.visualstudio.com/docs/editor/userdefinedsnippets#_choice

2021-03-16 16:52 UTC, aeisenberg commented on extensions/ql-vscode/snippets.json
> +    "body": ["from $1", "where $2", "select $3"],
I find it easier to read if there are default values for each replacement step.

```suggestion
    "body": ["from ${1:params}", "where ${2:clause}", "select ${2:args}"],
```

2021-03-17 15:07 UTC, aeisenberg approved these changes
Nice work!

2021-03-17 15:43 UTC, merged

2021-03-19 17:13 UTC, aeisenberg commented
@github/docs-content-dsp Is this the kind of thing that should go in the documentation?

2021-03-22 14:40 UTC, shati-patel commented
> @github/docs-content-dsp Is this the kind of thing that should go in the documentation?

Looks exciting 😄 I've opened an internal docs issue where we can assess if/where we need to document this.